name: macOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup NuGet.exe
        uses: NuGet/setup-nuget@v1.0.2
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.6.0
      
      - name: Build Coyote projects
        run: ./Scripts/build.ps1
        shell: pwsh
      
      - name: Run Coyote Tests
        run: ./Scripts/run-tests.ps1
        shell: pwsh
        env:
          COYOTE_CLI_TELEMETRY_OPTOUT: 1
      
      - name: Build Coyote NuGet package
        run: dotnet pack ./Tools/Coyote/Coyote.csproj
        shell: pwsh
      
      - name: Test Coyote.CLI NuGet package
        run: ./Scripts/test-cli-package.ps1
        shell: pwsh
        env:
          COYOTE_CLI_TELEMETRY_OPTOUT: 1
      