name: Linux CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup NuGet.exe
        uses: NuGet/setup-nuget@v1.0.2
      
      - name: Setup .NET 5.x SDK
        uses: actions/setup-dotnet@v1.7.2

      - name: Setup .NET Core 3.1.x SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '3.1.x'
      
      - name: Set environment variables
        run: echo "COYOTE_CLI_TELEMETRY_OPTOUT=1" >> $GITHUB_ENV

      - name: Build Coyote projects
        run: ./Scripts/build.ps1 -local $false
        shell: pwsh
      
      - name: Run Coyote Tests
        run: ./Scripts/run-tests.ps1
        shell: pwsh
      
      - name: Build Coyote NuGet package
        run: dotnet pack ./Tools/Coyote/Coyote.csproj
        shell: pwsh
      
      - name: Test Coyote.CLI NuGet package
        run: ./Scripts/test-cli-package.ps1
        shell: pwsh
      